### ISSUE TITLE
Add complete documentation to existing aliases and Mercurial.NET types

### ISSUE THREAD

**Issue by vCipher** [vCipher/Cake.Hg#10]
Add wiki pages to describe how to work with cake.hg and mercurial.net

**Comment by gep13** [comment]
@vCipher rather than creating wiki pages, you might want to look at using Wyam, which is already built into Cake.Recipe.  This would allow you to create a website similar to the following:

https://cake-contrib.github.io/Cake.Recipe/docs/

Just an idea 😄

**Comment by vCipher** [comment]
@gep13 Yes, I have thought about it. But I have some dependecies to Mercurial.NET library and have no idea how to generate docs with its types.

**Comment by gep13** [comment]
You can point Wyam at the source files, or the assembly, and it can generate the documentation for those types (assuming that there are some XML comments available).

**Comment by vCipher** [comment]
@gep13 Ok. But when I add assemlies to config.wyam like that:
```
#a "**/Cake.Hg.dll"
#a "**/Cake.Core.dll"
#a "**/Mercurial.Net.dll"
```
nothing chages.

**Comment by gep13** [comment]
Currently, within Cake.Recipe, it will be invoking Wyam through the Cake build script, which is set up to use Source Files.  You may have to do some work through the BuildParameters to change the way that Wyam is being called.

i.e. if you call Wyam directly, rather than invoking through Cake.Recipe, does it generate the required output?

**Comment by vCipher** [comment]
@gep13  No. I get something like this
![image](https://user-images.githubusercontent.com/5900205/32727823-c21240a6-c8c9-11e7-87d7-5b015d165794.png)

**Comment by gep13** [comment]
So, just to confirm, this is what you get when you call the wyam.exe directly from the command line?  Or that is what you get when you run `.\build.ps1 -target preview`?

**Comment by vCipher** [comment]
@gep13 This is what I get when I call `wyam -p -r Docs` directly.

**Comment by gep13** [comment]
Can you provide the config.wyam that you are currently using?  Perhaps we can get @daveaglick to provide some guidance here as well.

**Comment by vCipher** [comment]
@gep13 Yes, of course.
config.wyam:
```
#recipe Docs

// Customize your settings and add new ones here
Settings[Keys.Host] = "host.com";
Settings[DocsKeys.Title] = "My Docs";

#a "**/Cake.Hg.dll"
#a "**/Cake.Core.dll"
#a "**/Mercurial.Net.dll"
```
project structure:
```
/input
    /Cake.Hg.dll
    /Cake.Hg.xml
    /Cake.Core.dll
    /Cake.Core.xml
    /Mercurial.Net.dll
    /Mercurial.Net.xml
/src
    /all sources...
```

I call `wyam -p -r Docs` from `/` directory.

**Comment by vCipher** [comment]
@gep13 I got it! Wyam simply required to add `Settings[DocsKeys.AssemblyFiles] = "**/Mercurial.Net.dll";` setting line. Thank you!

**Comment by gep13** [comment]
:+1:  Hopefully, you should be able to add this, and still be able to use Cake.Recipe to push the changes to a GitHub Pages for displaying.

**Comment by vCipher** [comment]
@gep13 Yes, I going to add this config to project add use Cake.Recipe
