### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [vCipher/Cake.Hg#2]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by gep13** [comment]
@vCipher as a follow up, if you would be interested in moving this addin into the Cake-Contrib Organisation, to sit alongside the Cake.Git addin, then that is definitely something that we can chat about as well.

**Comment by vCipher** [comment]
@gep13 I really interested in moving this addin into the Cake-Contrib Organisation.

**Comment by vCipher** [comment]
@gep13 I added cake-contrib as co-owner to nuget. What's the next step?

**Comment by gep13** [comment]
@vCipher I have accepted the invite that you sent out, and the cake-contrib user is now a co-owner of the Cake.Hg NuGet package.  Thank you for doing this!

**Comment by gep13** [comment]
@vCipher in terms of adding Cake.Hg Project to the Cake-Contrib Organisation, the process is documented here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

The one step that needs your help would be to initially transfer the repo to my GitHub Account, and from there, I can do the other steps.

**Comment by gep13** [comment]
@vCipher please accept my apologies... I have just went to accept your repository transfer, but I have just got a warning that the Transfer has expired.  I took too long in getting to it.  Could you please attempt to transfer the repository again?  Thanks

**Comment by vCipher** [comment]
@gep13 I've just restarted transfer.

**Comment by gep13** [comment]
@vCipher Perfect, I have just transferred it into the Cake-Contrib Organisation.  I am running a script which synchronises some permissions for you across all projects and AppVeyor (which is the Continuous Integration Server that we use).  This will take a few minutes to complete, but once it has, you should have all the required permissions in order to continue maintaining this repository.

Please let me know if you have any questions.

**Comment by gep13** [comment]
@vCipher the process is now complete.  Again, please let me know if you have any questions.

**Comment by vCipher** [comment]
@gep13 Great! Thank you for your invitation.

**Comment by gep13** [comment]
@vCipher You are very welcome!  Thank you for creating this addin!
